version: '3.5'
services:
  api:
    image: flask_city_search_engine
    container_name: semaphore-flask_city_search_engine_1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/
    environment:
      - PORT=5000
